$engine: 3
$onesync: on
name: ESX Legacy
version: 0.3.8
author: ESX Framework
description: The official recipe of the most popular FiveM RP framework, containing Jobs, Housing, Vehicles & more!

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/esx-framework/ESX-recipes
    ref: legacy
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg
    
  - action: move_path
    src: ./tmp/recipe/myLogo.png
    dest: ./myLogo.png

  - action: move_path
    src: ./tmp/recipe/loadingscreen
    dest: ./resources/loadingscreen
  
  # Download basic resources and ESX dependencies

  - action: connect_database
  
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/esx-framework/esx-legacy
    ref: main
    dest: ./tmp/esx
    
  - action: move_path
    src: ./tmp/esx/[esx]
    dest: ./resources/[esx]

  - action: move_path
    src: ./tmp/esx/[esx_addons]
    dest: ./resources/[esx_addons]
    
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  - action: download_github
    src: https://github.com/EntityEvolution/ev-hud
    ref: main
    dest: ./resources/[hud]/ev-hud

  - action: download_github
    src: https://github.com/Benzo00/esx-radio
    ref: main
    dest: ./resources/[esx_addons]/esx-radio

  - action: query_database
    file: ./tmp/esx/[SQL]/legacy.sql

  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/oxmysql.zip
    
  ## Patching configs: HUD 
  - action: replace_string
    file: ./resources/[esx_addons]/esx_status/config.lua
    search: 'Config.Display        = true'
    replace: 'Config.Display        = false'

  - action: replace_string
    file: ./resources/[hud]/ev-hud/config/config.js
    search: 'Config.useFramework = false // Set to true to use ESX, VRP or QBCore'
    replace: 'Config.useFramework = true // Set to true to use ESX, VRP or QBCore'
  
  ## Patching configs: esx-radio
  - action: replace_string
    file: ./resources/[esx_addons]/esx-radio/config.lua
    search: 'Key = "UP"'
    replace: 'Key = "F5"'

  - action: replace_string
    mode: all_vars
    file: 
    - ./resources/loadingscreen/config.js

  ## Cleanup
  - action: remove_path
    path: ./tmp
  - action: remove_path
    path: ./resources/esx_example
  - action: remove_path
    path: ./resources/[esx_addons]/esx_whitelist
  - action: remove_path
    path: ./resources/[esx_addons]/esx_voice
  - action: remove_path
    path: ./resources/[esx_addons]/esx_phone
